#' Generate sequential date periods between two dates
#'
#' Creates a tibble of contiguous periods covering [start_date, end_date].
#' The length of each period is controlled by `by` (passed to [seq.Date()]),
#' and labels are built with optional `prefix`, `suffix`, and `sep`.
#'
#' @param start_date Date or character coercible to Date. Range start (inclusive).
#' @param end_date   Date or character coercible to Date. Range end (inclusive).
#' @param sep        String between start and end in each period label. Default `","`.
#' @param by         Interval passed to [seq.Date()] (e.g. `"1 month"`, `"3 months"`,
#'                   `"30 days"`, `"2 weeks"`). Default `"6 months"`.
#' @param prefix     String prepended to each label. Default `""`.
#' @param suffix     String appended to each label. Default `""`.
#'
#' @return A tibble with columns:
#' \describe{
#'   \item{start}{Start date of the period (inclusive).}
#'   \item{end}{End date of the period (inclusive).}
#'   \item{period}{Character label: `prefix + start + sep + end + suffix`.}
#' }
#'
#' @details
#' Periods are generated by `starts <- seq(start_date, end_date, by = by)`.
#' Each period's end is the day before the next period's start; the final
#' period ends at `end_date`. No alignment to calendar boundaries is applied.
#'
#' @examples
#' make_periods("2012-01-01", "2012-07-31", by = "3 months",
#'              prefix = "{", suffix = "}")
#' # -> 2012-01-01..2012-03-31, 2012-04-01..2012-06-30, 2012-07-01..2012-07-31
#'
#' @export
make_periods <- function(start_date, end_date,
                         sep = ",", by = "6 months",
                         prefix = "", suffix = "") {
    s <- lubridate::as_date(start_date)
    e <- lubridate::as_date(end_date)
    if (is.na(s) || is.na(e)) stop("start_date/end_date must be coercible to Date")
    if (s > e) {
        return(tibble::tibble(
            start = as.Date(character()),
            end   = as.Date(character()),
            period = character()
        ))
    }

    starts <- seq(from = s, to = e, by = by)
    ends <- c(starts[-1] - 1, e)

    tibble::tibble(
        start  = starts,
        end    = ends,
        period = paste0(prefix,
                        format(starts, "%Y-%m-%d"),
                        sep,
                        format(ends, "%Y-%m-%d"),
                        suffix)
    )
}
